name: JMeter Performance Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Apache JMeter
        run: |
          JMETER_VERSION=5.6.3
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
          echo "JMETER_HOME=$(pwd)/apache-jmeter-$JMETER_VERSION" >> $GITHUB_ENV
          echo "$JMETER_HOME/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          mkdir -p results
          jmeter -n -t test-plan.jmx -l results/jmeter-results.jtl -e -o results/html-report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: results/html-report
